# run: conda env create --file environment.yml
name: freq_fliers_notebooks
dependencies:
- anaconda
- jupyter
- jupyter-nbconvert
- matplotlib
- nltk
- numpy>=1.11.1
- pandas>=0.18.1
- pip
- psycopg2
- python==3.5.2
- scipy
- scikit-learn>=0.18
- sqlalchemy>=1.1.3
- pip:
  - pycorenlp
  - imbalanced-learn
